spring:
  mail:
   ##邮箱服务器地址
    ##QQ smtp.qq.com
    ##sina smtp.sina.cn
    ##aliyun smtp.aliyun.com
    ##163 smtp.163.com
    host: smtp.qq.com
    ##邮箱用户名
    username: 1071812786@qq.com
    ##邮箱密码（注意：qq邮箱应该使用独立密码，去qq邮箱设置里面获取）
    password: yoshtvjknkukbegi
    port: 25
    ##编码格式
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smth:
          auth: true
          starttls:
            enable: true
            required: true